= Parameters

The parent key for all of the following parameters is `renovate`.

== `namespace`

[horizontal]
type:: string
default:: `syn-renovate`

The namespace in which to deploy this component.


== `release_name`

[horizontal]
type:: string
default:: `${_instance}`

The Helm release name used for the Renovate deployment.
By default, the Commodore meta-parameter `parameters._instance` is used. `parameters._instance` is set to the aliased name used for instantiation or the component name for non-aliased instances.


== `images`

[horizontal]
type:: dictionary
default:: `{}`

Optional container image configuration.
This component intentionally doesn't pin a default Renovate image tag because Renovate releases very frequently.
Set the image tag explicitly in your cluster configuration via `helm_values.image.tag`.


== `charts`

[horizontal]
type:: dictionary

Dictionary containing the chart versions used by this component.


== `charts.renovate.version`

[horizontal]
type:: string
default:: See https://github.com/projectsyn/component-renovate/blob/master/class/defaults.yml[class/defaults.yml]

The Helm chart version used for this component.


== `charts.renovate.source`

[horizontal]
type:: string
default:: See https://github.com/projectsyn/component-renovate/blob/master/class/defaults.yml[class/defaults.yml]

The Helm chart source repository used by this component.


== `helm_values`

[horizontal]
type:: dict
default:: `{}`

All `helm_values` are passed to the Renovate Helm chart.
The component doesn't ship a default Renovate bot configuration.
You must provide either `helm_values.renovate.config` or `helm_values.renovate.existingConfigFile`.
For the supported self-hosted Renovate options, see https://docs.renovatebot.com/self-hosted-configuration/[the official Renovate self-hosted configuration docs].
For the supported Helm chart values, see https://github.com/renovatebot/helm-charts/tree/main/charts/renovate[the official Renovate Helm chart documentation].


== Example

[source,yaml]
----
namespace: example-namespace
----
